.Dd $Mdocdate$
.Dt LIBSLIST 3
.Os
.Sh NAME
.Nm LIBSLIST
.Nd statically-compiled singly-linked list library
.Sh SYNOPSIS
.In dlist.h
.Ft int
.Fo dlist_insert
.Fa "struct dlist_node **head"
.Fa "void *entry"
.Fa "size_t size"
.Fc
.Ft int
.Fo dlist_append
.Fa "struct dlist_node **head"
.Fa "void *entry"
.Fa "size_t size"
.Fc
.Ft int
.Fo dlist_insert_after
.Fa "struct dlist_node *head"
.Fa "void *entry"
.Fa "size_t size"
.Fc
.Fa ssize_t
.Fo dlist_search
.Fa "struct dlist_node *head"
.Fa "void *entry"
.Fa "size_t size"
.Fc
.Ft "struct dlist_node	*"
.Fo dlist_locate
.Fa "struct dlist_node *head"
.Fa "size_t index"
.Fc
.Ft int
.Fo dlist_remove
.Fa "struct dlist_node **head"
.Fa "void *entry"
.Fa "size_t size"
.Fc
.Ft int
.Fo dlist_remove_head
.Fa "struct dlist_node **head"
.Fc
.Ft int
.Fo dlist_remove_tail
.Fa "struct dlist_node **head"
.Fc
.Ft size_t
.Fo dlist_length
.Fa "struct dlist_node *head"
.Fc
.Ft void
.Fo dlist_destroy
.Fa "struct dlist_node **head"
.Fc
.Sh DESCRIPTION
.Nm
is a statically-compiled library providing a singly linked list. The lists are
based on the
.Nm dlist_node
structure, defined as
.Bd -literal
struct dlist_node {
	 void			*entry;
	 size_t			 size;
	 struct dlist_node	*next;
};
.Ed
Programs using this list should keep track of a particular
.Nm dlist_node
that points to the head of the list. An empty list is signified by a NULL
head. New nodes may be inserted and appended with the
.Nm dlist_insert
and
.Nm dlist_append
functions; inserting a node in the middle of the list is done with the
.Nm dlist_insert_after
function. The
.Nm dlist_search
function returns the position in the list of the node with the entry passed
in as an argument;
.Nm dlist_locate
returns the node at the index passed in.
.Nm dlist_remove
removes the first node matching the entry passed in;
.Nm dlist_remove_head
and
.Nm dlist_remove_tail
remove the head and tail of the list, respectively.
.Nm dlist_tail
returns the length of the list.
.Nm dlist_destroy
must be used to destroy a list to make sure that it is properly deallocated.
.Sh RETURN VALUES
The functions returning an integer return a -1 on failure and a 0 on success;
.Nm dlist_search
returns the index of the node being searched for, and -1 if it could not be
found.
.Nm dlist_locate
returns the node at the requested index, and NULL if the index is outside
is outside of the list.
.Nm dlist_length
returns the length of the list.
.Sh ERRORS
The insertion functions will return an error if there was a problem allocating
memory; the remove functions return an error if the node couldn't be removed.
.\" .Sh SEE ALSO
.Sh STANDARDS
.Nm
is written in ANSI C and conforms to SUSv4.
.\" .Sh HISTORY
.Sh AUTHORS
.Nm
was written by
.An Kyle Isom Aq Mt kyle@tyrfingr.is .
.Sh CAVEATS
The entries passed into the insertion and search functions must be able
to be duplicated with
.Nm memcpy .
.Sh BUGS
Please report all bugs to the author.
